Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Python37\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Python37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Python37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Python37\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "C:\Python37\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Python37\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Python37\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
import numpy as np
import math

plt.rcParams["figure.figsize"] = [7.50, 7.50]
plt.rcParams["figure.autolayout"] = True

x = np.linspace(-2,2,100)

axes = fig.add_axes([0, 0, 2, 2])
axes.plot(x,x**2)
plt.title("inverse function theorem")
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_7400\3108555546.py[0m in [0;36m<module>[1;34m[0m
[0;32m      8[0m [0mx[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0mlinspace[0m[1;33m([0m[1;33m-[0m[1;36m2[0m[1;33m,[0m[1;36m2[0m[1;33m,[0m[1;36m100[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      9[0m [1;33m[0m[0m
[1;32m---> 10[1;33m [0maxes[0m [1;33m=[0m [0mfig[0m[1;33m.[0m[0madd_axes[0m[1;33m([0m[1;33m[[0m[1;36m0[0m[1;33m,[0m [1;36m0[0m[1;33m,[0m [1;36m2[0m[1;33m,[0m [1;36m2[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     11[0m [0maxes[0m[1;33m.[0m[0mplot[0m[1;33m([0m[0mx[0m[1;33m,[0m[0mx[0m[1;33m**[0m[1;36m2[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     12[0m [0mplt[0m[1;33m.[0m[0mtitle[0m[1;33m([0m[1;34m"inverse function theorem"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'fig' is not defined
NameError: name 'fig' is not defined

